//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathFinder.DataTransferObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PathFinder.DataTransferObjects.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Account.
        /// </summary>
        public static string AcceptAccount {
            get {
                return ResourceManager.GetString("AcceptAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to accept account for user.
        /// </summary>
        public static string AcceptMessage {
            get {
                return ResourceManager.GetString("AcceptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access my dashboard.
        /// </summary>
        public static string AccessMyDashboard {
            get {
                return ResourceManager.GetString("AccessMyDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can contact the Human Resources Department to find out the details.
        /// </summary>
        public static string Account_Communicate {
            get {
                return ResourceManager.GetString("Account_Communicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is still under review.
        /// </summary>
        public static string AccountPending {
            get {
                return ResourceManager.GetString("AccountPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until your account is reviewed and a personal email will be sent to confirm that your account has been activated.
        /// </summary>
        public static string AccountPending_Waiting {
            get {
                return ResourceManager.GetString("AccountPending_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal account has been rejected.
        /// </summary>
        public static string AccountRejected {
            get {
                return ResourceManager.GetString("AccountRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your data and re-register again.
        /// </summary>
        public static string AccountRejected_Response {
            get {
                return ResourceManager.GetString("AccountRejected_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acre.
        /// </summary>
        public static string Acre {
            get {
                return ResourceManager.GetString("Acre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add land.
        /// </summary>
        public static string AddLand {
            get {
                return ResourceManager.GetString("AddLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added.
        /// </summary>
        public static string AddSuccessMessage {
            get {
                return ResourceManager.GetString("AddSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By sign up you agree to the &quot;terms &amp; conditions&quot;.
        /// </summary>
        public static string AgreeTerms {
            get {
                return ResourceManager.GetString("AgreeTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural land area.
        /// </summary>
        public static string AgriculturalLandArea {
            get {
                return ResourceManager.GetString("AgriculturalLandArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural waste.
        /// </summary>
        public static string AgriculturalWaste {
            get {
                return ResourceManager.GetString("AgriculturalWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed extensions : (&quot;.jpg&quot;, &quot;.png&quot;, &quot;.pdf&quot;, &quot;.jpeg&quot;).
        /// </summary>
        public static string AllowedExtensions {
            get {
                return ResourceManager.GetString("AllowedExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvals.
        /// </summary>
        public static string Approvals {
            get {
                return ResourceManager.GetString("Approvals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArName.
        /// </summary>
        public static string ArName {
            get {
                return ResourceManager.GetString("ArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        public static string Assessment {
            get {
                return ResourceManager.GetString("Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IWEX platform aims to offer users access to information, resources, and services focused on waste management and recycling and economic development of the industrial and agricultural sectors..
        /// </summary>
        public static string bannreOneDescription {
            get {
                return ResourceManager.GetString("bannreOneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To empower waste management and recycling.
        /// </summary>
        public static string bannreOneTitle {
            get {
                return ResourceManager.GetString("bannreOneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Enabling factories, companies, and farmers to exchange their industrial and agricultural waste to improve the usability and functionality of the economic ecosystem and the industrial process essentially increasing efficiency and economic development.
        /// </summary>
        public static string bannreTwoDescription {
            get {
                return ResourceManager.GetString("bannreTwoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable today and tomorrow&apos;s innovation.
        /// </summary>
        public static string bannreTwoTitle {
            get {
                return ResourceManager.GetString("bannreTwoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Chart.
        /// </summary>
        public static string BarChart {
            get {
                return ResourceManager.GetString("BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiaries.
        /// </summary>
        public static string Beneficiaries {
            get {
                return ResourceManager.GetString("Beneficiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building number.
        /// </summary>
        public static string BuildingNumber {
            get {
                return ResourceManager.GetString("BuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carat.
        /// </summary>
        public static string Carat {
            get {
                return ResourceManager.GetString("Carat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card owner name.
        /// </summary>
        public static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of waste category for demand.
        /// </summary>
        public static string CategoryWasteTransactionDemandCount {
            get {
                return ResourceManager.GetString("CategoryWasteTransactionDemandCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of waste category for supply.
        /// </summary>
        public static string CategoryWasteTransactionSupplyCount {
            get {
                return ResourceManager.GetString("CategoryWasteTransactionSupplyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDA coordinator.
        /// </summary>
        public static string CDACoordinator {
            get {
                return ResourceManager.GetString("CDACoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification.
        /// </summary>
        public static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check code.
        /// </summary>
        public static string CheckCode {
            get {
                return ResourceManager.GetString("CheckCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Code.
        /// </summary>
        public static string CodeWrong {
            get {
                return ResourceManager.GetString("CodeWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development partner.
        /// </summary>
        public static string Collaborator {
            get {
                return ResourceManager.GetString("Collaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial (Brand) name.
        /// </summary>
        public static string CommercialName {
            get {
                return ResourceManager.GetString("CommercialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why you do not have commercial register ? .
        /// </summary>
        public static string CommercialRegisterMessage {
            get {
                return ResourceManager.GetString("CommercialRegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial registration number.
        /// </summary>
        public static string CommercialRegistrationNumber {
            get {
                return ResourceManager.GetString("CommercialRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial registration office.
        /// </summary>
        public static string CommercialRegistrationOffice {
            get {
                return ResourceManager.GetString("CommercialRegistrationOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Level.
        /// </summary>
        public static string CommunityLevel {
            get {
                return ResourceManager.GetString("CommunityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company / Factory.
        /// </summary>
        public static string Company_Factory {
            get {
                return ResourceManager.GetString("Company_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial sector (activity).
        /// </summary>
        public static string CompanyActivity {
            get {
                return ResourceManager.GetString("CompanyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Category.
        /// </summary>
        public static string CompanyCategory {
            get {
                return ResourceManager.GetString("CompanyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        public static string CompanyDetails {
            get {
                return ResourceManager.GetString("CompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company governing entity.
        /// </summary>
        public static string CompanyGoverningEntity {
            get {
                return ResourceManager.GetString("CompanyGoverningEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company industrial area.
        /// </summary>
        public static string CompanyIndustrialArea {
            get {
                return ResourceManager.GetString("CompanyIndustrialArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company nationality.
        /// </summary>
        public static string CompanyNationality {
            get {
                return ResourceManager.GetString("CompanyNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company office.
        /// </summary>
        public static string CompanyOffice {
            get {
                return ResourceManager.GetString("CompanyOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company phone number.
        /// </summary>
        public static string CompanyPhoneNumber {
            get {
                return ResourceManager.GetString("CompanyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanySector.
        /// </summary>
        public static string CompanySector {
            get {
                return ResourceManager.GetString("CompanySector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyStatus.
        /// </summary>
        public static string CompanyStatus {
            get {
                return ResourceManager.GetString("CompanyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company waste output.
        /// </summary>
        public static string CompanyWasteOutput {
            get {
                return ResourceManager.GetString("CompanyWasteOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to ask me any question or let&apos;s do to talk about our future collaboration..
        /// </summary>
        public static string Contact_messege {
            get {
                return ResourceManager.GetString("Contact_messege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us Dashboard.
        /// </summary>
        public static string ContactUsDashboard {
            get {
                return ResourceManager.GetString("ContactUsDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of waste.
        /// </summary>
        public static string CountWaste {
            get {
                return ResourceManager.GetString("CountWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of waste to be purchased.
        /// </summary>
        public static string CountWasteDemand {
            get {
                return ResourceManager.GetString("CountWasteDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of waste to be sold.
        /// </summary>
        public static string CountWasteSupply {
            get {
                return ResourceManager.GetString("CountWasteSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course code.
        /// </summary>
        public static string CourseCode {
            get {
                return ResourceManager.GetString("CourseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course detials.
        /// </summary>
        public static string CourseDetials {
            get {
                return ResourceManager.GetString("CourseDetials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string Definitions {
            get {
                return ResourceManager.GetString("Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted.
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disability.
        /// </summary>
        public static string Disability {
            get {
                return ResourceManager.GetString("Disability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Level.
        /// </summary>
        public static string EducationLevel {
            get {
                return ResourceManager.GetString("EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Enter a valid email address for messages and notifications).
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engagement.
        /// </summary>
        public static string Engagement {
            get {
                return ResourceManager.GetString("Engagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engagement Level.
        /// </summary>
        public static string EngagementLevel {
            get {
                return ResourceManager.GetString("EngagementLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engagement Modality.
        /// </summary>
        public static string EngagementModality {
            get {
                return ResourceManager.GetString("EngagementModality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email or Phone Number.
        /// </summary>
        public static string Enter_Your_Email_Phone {
            get {
                return ResourceManager.GetString("Enter_Your_Email_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Origin.
        /// </summary>
        public static string EnterpriseOrigin {
            get {
                return ResourceManager.GetString("EnterpriseOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Type.
        /// </summary>
        public static string EnterpriseType {
            get {
                return ResourceManager.GetString("EnterpriseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepreneur.
        /// </summary>
        public static string Entrepreneur {
            get {
                return ResourceManager.GetString("Entrepreneur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepreneurial stage.
        /// </summary>
        public static string Entrepreneurial_stage {
            get {
                return ResourceManager.GetString("Entrepreneurial stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage of entrepreneurship.
        /// </summary>
        public static string EntrepreneurialStage {
            get {
                return ResourceManager.GetString("EntrepreneurialStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer.
        /// </summary>
        public static string Farmer {
            get {
                return ResourceManager.GetString("Farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer card details.
        /// </summary>
        public static string FarmerCard {
            get {
                return ResourceManager.GetString("FarmerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First contact person.
        /// </summary>
        public static string FirstContactPerson {
            get {
                return ResourceManager.GetString("FirstContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Eng.
        /// </summary>
        public static string FirstLanguage {
            get {
                return ResourceManager.GetString("FirstLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password ?.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password ?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name (triplex, quaternary).
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geleh.
        /// </summary>
        public static string Geleh {
            get {
                return ResourceManager.GetString("Geleh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Password.
        /// </summary>
        public static string GeneratePassword {
            get {
                return ResourceManager.GetString("GeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in Touch.
        /// </summary>
        public static string Get_in_Touch {
            get {
                return ResourceManager.GetString("Get-in-Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governorate.
        /// </summary>
        public static string Governorate {
            get {
                return ResourceManager.GetString("Governorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you already have an account?.
        /// </summary>
        public static string HaveAccount {
            get {
                return ResourceManager.GetString("HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the .
        /// </summary>
        public static string I_agree_to_the {
            get {
                return ResourceManager.GetString("I_agree_to_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL.
        /// </summary>
        public static string ImageURL {
            get {
                return ResourceManager.GetString("ImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial Area.
        /// </summary>
        public static string IndustrialArea {
            get {
                return ResourceManager.GetString("IndustrialArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial waste.
        /// </summary>
        public static string IndustrialWaste {
            get {
                return ResourceManager.GetString("IndustrialWaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industries Dashboard.
        /// </summary>
        public static string IndustriesDashboard {
            get {
                return ResourceManager.GetString("IndustriesDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input error.
        /// </summary>
        public static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Research.
        /// </summary>
        public static string InterestResearch {
            get {
                return ResourceManager.GetString("InterestResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervention.
        /// </summary>
        public static string Intervention {
            get {
                return ResourceManager.GetString("Intervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOS.
        /// </summary>
        public static string IOS {
            get {
                return ResourceManager.GetString("IOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client in the agricultural bank.
        /// </summary>
        public static string IsAgriculturalBank {
            get {
                return ResourceManager.GetString("IsAgriculturalBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member of the agricultural society.
        /// </summary>
        public static string IsAgriculturalSociety {
            get {
                return ResourceManager.GetString("IsAgriculturalSociety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a commercial register?.
        /// </summary>
        public static string IsCommercialRegister {
            get {
                return ResourceManager.GetString("IsCommercialRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Land {
            get {
                return ResourceManager.GetString("Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land address.
        /// </summary>
        public static string LandAddress {
            get {
                return ResourceManager.GetString("LandAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of land .
        /// </summary>
        public static string LandArea {
            get {
                return ResourceManager.GetString("LandArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land waste output.
        /// </summary>
        public static string LandWasteOutput {
            get {
                return ResourceManager.GetString("LandWasteOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease document.
        /// </summary>
        public static string LeaseDocument {
            get {
                return ResourceManager.GetString("LeaseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogInHere {
            get {
                return ResourceManager.GetString("LogInHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count user that login per days.
        /// </summary>
        public static string LoginPerDays {
            get {
                return ResourceManager.GetString("LoginPerDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop main partner.
        /// </summary>
        public static string MainPartner {
            get {
                return ResourceManager.GetString("MainPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company main shareholder .
        /// </summary>
        public static string MainShareholder {
            get {
                return ResourceManager.GetString("MainShareholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiales of interest.
        /// </summary>
        public static string MaterialesOfInterest {
            get {
                return ResourceManager.GetString("MaterialesOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials Of Interest.
        /// </summary>
        public static string MaterialsOfInterest {
            get {
                return ResourceManager.GetString("MaterialsOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 5 megabytes.
        /// </summary>
        public static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEL coordinator.
        /// </summary>
        public static string MELCordinator {
            get {
                return ResourceManager.GetString("MELCordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type.
        /// </summary>
        public static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry.
        /// </summary>
        public static string Ministry {
            get {
                return ResourceManager.GetString("Ministry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification Date.
        /// </summary>
        public static string ModificationDate {
            get {
                return ResourceManager.GetString("ModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string NationalID {
            get {
                return ResourceManager.GetString("NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Member.
        /// </summary>
        public static string New_Member {
            get {
                return ResourceManager.GetString("New_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGO.
        /// </summary>
        public static string NGO {
            get {
                return ResourceManager.GetString("NGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoAnswer.
        /// </summary>
        public static string NoAnswer {
            get {
                return ResourceManager.GetString("NoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For contact and notifications.
        /// </summary>
        public static string NotficationEmail {
            get {
                return ResourceManager.GetString("NotficationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives.
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other contact person.
        /// </summary>
        public static string OtherContactPerson {
            get {
                return ResourceManager.GetString("OtherContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Recent News.
        /// </summary>
        public static string OurRecentNews {
            get {
                return ResourceManager.GetString("OurRecentNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner/Tenant.
        /// </summary>
        public static string OwnerOrTenant {
            get {
                return ResourceManager.GetString("OwnerOrTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Type.
        /// </summary>
        public static string PartnerType {
            get {
                return ResourceManager.GetString("PartnerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +20 XXXXXXXXX.
        /// </summary>
        public static string PhonePlaceholder {
            get {
                return ResourceManager.GetString("PhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie Chart.
        /// </summary>
        public static string PieChart {
            get {
                return ResourceManager.GetString("PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place description.
        /// </summary>
        public static string PlaceDescription {
            get {
                return ResourceManager.GetString("PlaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possession document.
        /// </summary>
        public static string PossessionDocument {
            get {
                return ResourceManager.GetString("PossessionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted by.
        /// </summary>
        public static string PostedBy {
            get {
                return ResourceManager.GetString("PostedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Sector.
        /// </summary>
        public static string PrivateSector {
            get {
                return ResourceManager.GetString("PrivateSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Status.
        /// </summary>
        public static string ProfileStatus {
            get {
                return ResourceManager.GetString("ProfileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore on IWEX best &amp; largest Bidding marketplace with our beautiful Bidding products. We want to be a part of your smile, success and future growth..
        /// </summary>
        public static string RecentNewsDescription {
            get {
                return ResourceManager.GetString("RecentNewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comapnies that are registered per Covernorate.
        /// </summary>
        public static string RegisterCompanies {
            get {
                return ResourceManager.GetString("RegisterCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies &amp; Farmer Dashboar.
        /// </summary>
        public static string RegisterCompaniesAndFarmersDashboard {
            get {
                return ResourceManager.GetString("RegisterCompaniesAndFarmersDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies and Farmers that are registered per Month.
        /// </summary>
        public static string RegisterCompanyFarmer {
            get {
                return ResourceManager.GetString("RegisterCompanyFarmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Dashboard.
        /// </summary>
        public static string RegisterDashboard {
            get {
                return ResourceManager.GetString("RegisterDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmers that are registered per Month.
        /// </summary>
        public static string RegisterFarmers {
            get {
                return ResourceManager.GetString("RegisterFarmers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered a new.
        /// </summary>
        public static string RegisterMessage {
            get {
                return ResourceManager.GetString("RegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new user has been registered.
        /// </summary>
        public static string RegisterMessageTitle {
            get {
                return ResourceManager.GetString("RegisterMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in commercial register.
        /// </summary>
        public static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of user that registers.
        /// </summary>
        public static string RegisterUserCount {
            get {
                return ResourceManager.GetString("RegisterUserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users Dashboard.
        /// </summary>
        public static string RegisterUserDashboard {
            get {
                return ResourceManager.GetString("RegisterUserDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of user that registers percentage.
        /// </summary>
        public static string RegisterUserPercentage {
            get {
                return ResourceManager.GetString("RegisterUserPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Account.
        /// </summary>
        public static string RejectedAccount {
            get {
                return ResourceManager.GetString("RejectedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reject account for user.
        /// </summary>
        public static string RejectMessage {
            get {
                return ResourceManager.GetString("RejectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Image.
        /// </summary>
        public static string RemoveImage {
            get {
                return ResourceManager.GetString("RemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        public static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher.
        /// </summary>
        public static string Researcher {
            get {
                return ResourceManager.GetString("Researcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Institution.
        /// </summary>
        public static string ResearchInstitution {
            get {
                return ResourceManager.GetString("ResearchInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Specialization.
        /// </summary>
        public static string ResearchSpecialization {
            get {
                return ResourceManager.GetString("ResearchSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahm.
        /// </summary>
        public static string Sahm {
            get {
                return ResourceManager.GetString("Sahm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Phone.
        /// </summary>
        public static string SecondaryPhone {
            get {
                return ResourceManager.GetString("SecondaryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Ar.
        /// </summary>
        public static string SecondLanguage {
            get {
                return ResourceManager.GetString("SecondLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary phone number.
        /// </summary>
        public static string SecondPhoneNumber {
            get {
                return ResourceManager.GetString("SecondPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compant sencond main shareholder.
        /// </summary>
        public static string SecondShareholder {
            get {
                return ResourceManager.GetString("SecondShareholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop second main partner.
        /// </summary>
        public static string SencondPartner {
            get {
                return ResourceManager.GetString("SencondPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        public static string Send_email {
            get {
                return ResourceManager.GetString("Send_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string Send_Message {
            get {
                return ResourceManager.GetString("Send_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string SexMainShareholderGender {
            get {
                return ResourceManager.GetString("SexMainShareholderGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shareholder.
        /// </summary>
        public static string Shareholder {
            get {
                return ResourceManager.GetString("Shareholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up Here.
        /// </summary>
        public static string SignUp_here {
            get {
                return ResourceManager.GetString("SignUp_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name.
        /// </summary>
        public static string StreetName {
            get {
                return ResourceManager.GetString("StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-industrial sector.
        /// </summary>
        public static string SubIndustrialSector {
            get {
                return ResourceManager.GetString("SubIndustrialSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Stories.
        /// </summary>
        public static string Success_Stories {
            get {
                return ResourceManager.GetString("Success_Stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success message.
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration request has been sended.
        /// </summary>
        public static string SuccessRegister {
            get {
                return ResourceManager.GetString("SuccessRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until then, you can go to the platform to see all our latest news.
        /// </summary>
        public static string SuccessRegisterResult {
            get {
                return ResourceManager.GetString("SuccessRegisterResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We thank you, your effective registration request has been received.
        /// </summary>
        public static string SuccessRegisterThanks {
            get {
                return ResourceManager.GetString("SuccessRegisterThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for your request and you will receive a message via email and phone number about the status of your request when it is answered..
        /// </summary>
        public static string SuccessRegisterWaiting {
            get {
                return ResourceManager.GetString("SuccessRegisterWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Stories.
        /// </summary>
        public static string SuccessStoriesTitle {
            get {
                return ResourceManager.GetString("SuccessStoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile has been succeded.
        /// </summary>
        public static string SuccessUpdateProfile {
            get {
                return ResourceManager.GetString("SuccessUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term &amp; Policy.
        /// </summary>
        public static string Term_And_Policy {
            get {
                return ResourceManager.GetString("Term_And_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOT.
        /// </summary>
        public static string TOT {
            get {
                return ResourceManager.GetString("TOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total category waste.
        /// </summary>
        public static string TotalCategoryWasteTransaction {
            get {
                return ResourceManager.GetString("TotalCategoryWasteTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of register users.
        /// </summary>
        public static string TotalUser {
            get {
                return ResourceManager.GetString("TotalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer’s name.
        /// </summary>
        public static string TrainerName {
            get {
                return ResourceManager.GetString("TrainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO. Of training days.
        /// </summary>
        public static string TrainingDays {
            get {
                return ResourceManager.GetString("TrainingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of disability.
        /// </summary>
        public static string TypeOfDisability {
            get {
                return ResourceManager.GetString("TypeOfDisability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated.
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Commercial Register.
        /// </summary>
        public static string UploadCommercialRegister {
            get {
                return ResourceManager.GetString("UploadCommercialRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Contact delegation of authority.
        /// </summary>
        public static string UploadContactDelegation {
            get {
                return ResourceManager.GetString("UploadContactDelegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload News Image.
        /// </summary>
        public static string UploadNewsImage {
            get {
                return ResourceManager.GetString("UploadNewsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload lease document.
        /// </summary>
        public static string UploadOriginalLeaseDocument {
            get {
                return ResourceManager.GetString("UploadOriginalLeaseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload possession document.
        /// </summary>
        public static string UploadOriginalPossessionDocument {
            get {
                return ResourceManager.GetString("UploadOriginalPossessionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload success stories image.
        /// </summary>
        public static string UploadSuccessStoriesImage {
            get {
                return ResourceManager.GetString("UploadSuccessStoriesImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Success Story Image.
        /// </summary>
        public static string UploadSuccessStoryImage {
            get {
                return ResourceManager.GetString("UploadSuccessStoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Dashboard.
        /// </summary>
        public static string UserLoginDashboard {
            get {
                return ResourceManager.GetString("UserLoginDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Login.
        /// </summary>
        public static string UsersLoginChart {
            get {
                return ResourceManager.GetString("UsersLoginChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste.
        /// </summary>
        public static string Waste {
            get {
                return ResourceManager.GetString("Waste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Category.
        /// </summary>
        public static string WasteCategory {
            get {
                return ResourceManager.GetString("WasteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Category Dashboard.
        /// </summary>
        public static string WasteCategoryDashboard {
            get {
                return ResourceManager.GetString("WasteCategoryDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Dashboard.
        /// </summary>
        public static string WasteDashboard {
            get {
                return ResourceManager.GetString("WasteDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Output.
        /// </summary>
        public static string WasteOutput {
            get {
                return ResourceManager.GetString("WasteOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesting waste purchase.
        /// </summary>
        public static string WastePurchase {
            get {
                return ResourceManager.GetString("WastePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Sub Category.
        /// </summary>
        public static string WasteSubCategory {
            get {
                return ResourceManager.GetString("WasteSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste to be purchased.
        /// </summary>
        public static string WastTransactionDemand {
            get {
                return ResourceManager.GetString("WastTransactionDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste to be sold.
        /// </summary>
        public static string WastTransactionSupply {
            get {
                return ResourceManager.GetString("WastTransactionSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome message.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To IWEX.
        /// </summary>
        public static string WellcomeIWEX {
            get {
                return ResourceManager.GetString("WellcomeIWEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace.
        /// </summary>
        public static string Workplace {
            get {
                return ResourceManager.GetString("Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace Environment.
        /// </summary>
        public static string WorkplaceEnvironment {
            get {
                return ResourceManager.GetString("WorkplaceEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkShop.
        /// </summary>
        public static string WorkShop {
            get {
                return ResourceManager.GetString("WorkShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop main sector.
        /// </summary>
        public static string WorkShopActivity {
            get {
                return ResourceManager.GetString("WorkShopActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop Details.
        /// </summary>
        public static string WorkShopDetails {
            get {
                return ResourceManager.GetString("WorkShopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop governing entity.
        /// </summary>
        public static string WorkShopGoverningEntity {
            get {
                return ResourceManager.GetString("WorkShopGoverningEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop headquarters nationality.
        /// </summary>
        public static string WorkshopHeadquartersNationality {
            get {
                return ResourceManager.GetString("WorkshopHeadquartersNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop industrial area.
        /// </summary>
        public static string WorkShopIndustrialArea {
            get {
                return ResourceManager.GetString("WorkShopIndustrialArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop office.
        /// </summary>
        public static string WorkShopOffice {
            get {
                return ResourceManager.GetString("WorkShopOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop waste output.
        /// </summary>
        public static string WorkShopWasteOutput {
            get {
                return ResourceManager.GetString("WorkShopWasteOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write message.
        /// </summary>
        public static string Write_Message {
            get {
                return ResourceManager.GetString("Write_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP code.
        /// </summary>
        public static string ZIPCode {
            get {
                return ResourceManager.GetString("ZIPCode", resourceCulture);
            }
        }
    }
}
