//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathFinder.DataTransferObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PathFinder.DataTransferObjects.Resources.ModelValidationResources", typeof(ModelValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is still under review.
        /// </summary>
        public static string AccountPending {
            get {
                return ResourceManager.GetString("AccountPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account registration has been rejected.
        /// </summary>
        public static string AccountRejected {
            get {
                return ResourceManager.GetString("AccountRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add success .
        /// </summary>
        public static string AddSuccessMessage {
            get {
                return ResourceManager.GetString("AddSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar. Name is required.
        /// </summary>
        public static string ArNameEmpty {
            get {
                return ResourceManager.GetString("ArNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You not have permission .
        /// </summary>
        public static string AuthonticationFaild {
            get {
                return ResourceManager.GetString("AuthonticationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center is empty.
        /// </summary>
        public static string CenterEmpty {
            get {
                return ResourceManager.GetString("CenterEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter character only.
        /// </summary>
        public static string CharacterOnly {
            get {
                return ResourceManager.GetString("CharacterOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to the terms.
        /// </summary>
        public static string CheckTermsConditionsEmpty {
            get {
                return ResourceManager.GetString("CheckTermsConditionsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is empty.
        /// </summary>
        public static string CityEmpty {
            get {
                return ResourceManager.GetString("CityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial name is empty.
        /// </summary>
        public static string CommercialNameEmpty {
            get {
                return ResourceManager.GetString("CommercialNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial register message is empty.
        /// </summary>
        public static string CommercialRegisterMessageEmpty {
            get {
                return ResourceManager.GetString("CommercialRegisterMessageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial registration number is empty.
        /// </summary>
        public static string CommercialRegistrationNumberEmpty {
            get {
                return ResourceManager.GetString("CommercialRegistrationNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial registration office is empty.
        /// </summary>
        public static string CommercialRegistrationOfficeEmpty {
            get {
                return ResourceManager.GetString("CommercialRegistrationOfficeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company activity is empty.
        /// </summary>
        public static string CompanyActivityEmpty {
            get {
                return ResourceManager.GetString("CompanyActivityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the location of the company on the map.
        /// </summary>
        public static string CompanyAddressMapEmpty {
            get {
                return ResourceManager.GetString("CompanyAddressMapEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company industrial is empty.
        /// </summary>
        public static string CompanyIndustrialEmpty {
            get {
                return ResourceManager.GetString("CompanyIndustrialEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the confirm password.
        /// </summary>
        public static string ConfirmPasswordEmpty {
            get {
                return ResourceManager.GetString("ConfirmPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password doesn&apos;t match, Type again !.
        /// </summary>
        public static string ConfirmPasswordValidation {
            get {
                return ResourceManager.GetString("ConfirmPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person name is empty.
        /// </summary>
        public static string ContactPersonNameEmpty {
            get {
                return ResourceManager.GetString("ContactPersonNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person phone is empty.
        /// </summary>
        public static string ContactPersonPhoneEmpty {
            get {
                return ResourceManager.GetString("ContactPersonPhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must insert one Crop at least.
        /// </summary>
        public static string CropEmpty {
            get {
                return ResourceManager.GetString("CropEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the email.
        /// </summary>
        public static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email already exists. Try to login instead.
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Enter a valid email address for messages and notifications).
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng. Name is required.
        /// </summary>
        public static string EngNameEmpty {
            get {
                return ResourceManager.GetString("EngNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepreneuria lstage is empty.
        /// </summary>
        public static string EntrepreneurialStageEmpty {
            get {
                return ResourceManager.GetString("EntrepreneurialStageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email already exists. Try to login instead.
        /// </summary>
        public static string ExistEmail {
            get {
                return ResourceManager.GetString("ExistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist phone number.
        /// </summary>
        public static string ExistPhoneNumber {
            get {
                return ResourceManager.GetString("ExistPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already Exists.
        /// </summary>
        public static string ExistUser {
            get {
                return ResourceManager.GetString("ExistUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an employee identification number that will not be repeated.
        /// </summary>
        public static string ExitEmployeeIdentify {
            get {
                return ResourceManager.GetString("ExitEmployeeIdentify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register.
        /// </summary>
        public static string FailedToRegister {
            get {
                return ResourceManager.GetString("FailedToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must upload Files.
        /// </summary>
        public static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is empty.
        /// </summary>
        public static string FirstNameEmpty {
            get {
                return ResourceManager.GetString("FirstNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex is empty.
        /// </summary>
        public static string GenderEmpty {
            get {
                return ResourceManager.GetString("GenderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid register or login type.
        /// </summary>
        public static string InvalidRegisterOrLoginType {
            get {
                return ResourceManager.GetString("InvalidRegisterOrLoginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid URL.
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land address is empty.
        /// </summary>
        public static string LandAddressEmpty {
            get {
                return ResourceManager.GetString("LandAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the location of the land on the map.
        /// </summary>
        public static string LandAddressMapEmpty {
            get {
                return ResourceManager.GetString("LandAddressMapEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land area is empty.
        /// </summary>
        public static string LandAreaEmpty {
            get {
                return ResourceManager.GetString("LandAreaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is empty.
        /// </summary>
        public static string LastNameEmpty {
            get {
                return ResourceManager.GetString("LastNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is 14 characters.
        /// </summary>
        public static string Length14 {
            get {
                return ResourceManager.GetString("Length14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is 16 characters.
        /// </summary>
        public static string Length16 {
            get {
                return ResourceManager.GetString("Length16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is 32 characters.
        /// </summary>
        public static string Length32 {
            get {
                return ResourceManager.GetString("Length32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is 5 characters.
        /// </summary>
        public static string Length5 {
            get {
                return ResourceManager.GetString("Length5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name is empty.
        /// </summary>
        public static string MiddleNameEmpty {
            get {
                return ResourceManager.GetString("MiddleNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry is empty.
        /// </summary>
        public static string MinistryEmpty {
            get {
                return ResourceManager.GetString("MinistryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID is empty.
        /// </summary>
        public static string NationalIDEmpty {
            get {
                return ResourceManager.GetString("NationalIDEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National is empty.
        /// </summary>
        public static string NationalityEmpty {
            get {
                return ResourceManager.GetString("NationalityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission.
        /// </summary>
        public static string NotHavePermission {
            get {
                return ResourceManager.GetString("NotHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the password.
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must between 12 and 20 character , symbol  and number.
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must have at least 1 capital letter..
        /// </summary>
        public static string PasswordValidationCapital {
            get {
                return ResourceManager.GetString("PasswordValidationCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must have at least 12 chars no longer than 20.
        /// </summary>
        public static string PasswordValidationLength {
            get {
                return ResourceManager.GetString("PasswordValidationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must have at least 1 number..
        /// </summary>
        public static string PasswordValidationNumber {
            get {
                return ResourceManager.GetString("PasswordValidationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must have at least 1 special char..
        /// </summary>
        public static string PasswordValidationSpecial {
            get {
                return ResourceManager.GetString("PasswordValidationSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the phone number.
        /// </summary>
        public static string PhoneNumberEmpty {
            get {
                return ResourceManager.GetString("PhoneNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number.
        /// </summary>
        public static string PleaseEnterAValidNumber {
            get {
                return ResourceManager.GetString("PleaseEnterAValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter value.
        /// </summary>
        public static string PleaseEnterValue {
            get {
                return ResourceManager.GetString("PleaseEnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register name is empty.
        /// </summary>
        public static string RegisterNameEmpty {
            get {
                return ResourceManager.GetString("RegisterNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        public static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required !!!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research institution is empty.
        /// </summary>
        public static string ResearchInstitutionEmpty {
            get {
                return ResourceManager.GetString("ResearchInstitutionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research specialization is empty.
        /// </summary>
        public static string ResearchSpecializationEmpty {
            get {
                return ResourceManager.GetString("ResearchSpecializationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select role.
        /// </summary>
        public static string RoleEmpty {
            get {
                return ResourceManager.GetString("RoleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-industrial sector.
        /// </summary>
        public static string SubIndustrialSector {
            get {
                return ResourceManager.GetString("SubIndustrialSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success message.
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your mail or mobile to login please.
        /// </summary>
        public static string UserEmailOrMobileEmpty {
            get {
                return ResourceManager.GetString("UserEmailOrMobileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address or password you entered was incorrect..
        /// </summary>
        public static string UserEmailOrMobileValid {
            get {
                return ResourceManager.GetString("UserEmailOrMobileValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active.
        /// </summary>
        public static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter vaild number.
        /// </summary>
        public static string VaildNumber {
            get {
                return ResourceManager.GetString("VaildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid double number.
        /// </summary>
        public static string ValidDoubleNumber {
            get {
                return ResourceManager.GetString("ValidDoubleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid e-mail address.
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid integer number.
        /// </summary>
        public static string ValidIntNumber {
            get {
                return ResourceManager.GetString("ValidIntNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value (zero is allowed).
        /// </summary>
        public static string ValidIntOrZero {
            get {
                return ResourceManager.GetString("ValidIntOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone.
        /// </summary>
        public static string ValidPhone {
            get {
                return ResourceManager.GetString("ValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
    }
}
